"""
Generation API endpoints.

POST /generate      — enqueue a new generation job
GET  /status/{id}   — poll job progress & status
GET  /story/{id}    — retrieve the generated story JSON
GET  /download/{id} — download the placeholder MP4
"""
import os
from typing import List, Optional
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

from app.engines.job_manager import job_manager

router = APIRouter()


# ── Request / response schemas ────────────────────────────────────────────────

class GenerateRequest(BaseModel):
    prompt: str


class CompleteVideoRequest(BaseModel):
    genre: str = "Fantasy"
    theme: str = "Magic School"
    duration: int = 60
    language: str = "English"


class JobResponse(BaseModel):
    job_id: str
    status: str
    video_path: Optional[str] = None


class StatusResponse(BaseModel):
    job_id: str
    status: str
    progress: float
    story_id: Optional[str] = None
    error_message: Optional[str] = None
    result_path: Optional[str] = None
    video_path: Optional[str] = None


class CharacterSchema(BaseModel):
    name: str
    description: str


class SceneSchema(BaseModel):
    scene_number: int
    prompt: str
    dialogue: str


class StoryResponse(BaseModel):
    story_id: str
    job_id: str
    title: str
    summary: str
    characters: List[CharacterSchema]
    scenes: List[SceneSchema]


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.post("/generate", response_model=JobResponse, summary="Enqueue a generation job")
async def generate(request: GenerateRequest):
    """Submit a user prompt and receive a job_id for tracking."""
    job_id = job_manager.enqueue_job(request.prompt)
    return JobResponse(job_id=job_id, status="queued")


@router.post("/generate-complete-video", response_model=JobResponse, summary="Enqueue a complete video generation job")
async def generate_complete_video(request: CompleteVideoRequest):
    """Create a story-driven video pipeline with characters, prompts, voice, subtitles, music, and final composition."""
    job_id = job_manager.enqueue_complete_video_job(request.model_dump())
    return JobResponse(job_id=job_id, status="queued")


@router.get("/status/{job_id}", response_model=StatusResponse, summary="Poll job status")
async def get_status(job_id: str):
    """Return current status and progress for a job."""
    job = job_manager.get_job(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    result_path = job.get("result_path")
    return StatusResponse(
        job_id=job["id"],
        status=job["status"],
        progress=job["progress"],
        story_id=job.get("story_id"),
        error_message=job.get("error_message"),
        result_path=result_path,
        video_path=result_path,
    )


@router.get("/story/{job_id}", response_model=StoryResponse, summary="Get generated story")
async def get_story(job_id: str):
    """Return the full story JSON generated by Ollama for a completed job."""
    from app.core.database import SessionLocal
    from app.models.story import Story

    db = SessionLocal()
    try:
        story = db.query(Story).filter(Story.job_id == job_id).first()
        if not story:
            raise HTTPException(
                status_code=404,
                detail="Story not found. Job may still be processing.",
            )
        data = story.story_data
        return StoryResponse(
            story_id=story.id,
            job_id=job_id,
            title=data.get("title", ""),
            summary=data.get("summary", ""),
            characters=[CharacterSchema(**c) for c in data.get("characters", [])],
            scenes=[SceneSchema(**s) for s in data.get("scenes", [])],
        )
    finally:
        db.close()


@router.get("/download/{job_id}", summary="Download placeholder MP4")
async def download(job_id: str):
    """Stream the generated placeholder video file."""
    job = job_manager.get_job(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job not found")
    if not job.get("result_path"):
        raise HTTPException(status_code=202, detail="Job not yet completed")
    result_path = job["result_path"]
    if not os.path.isfile(result_path):
        raise HTTPException(status_code=404, detail="Output file not found on disk")
    return FileResponse(
        path=result_path,
        media_type="video/mp4",
        filename=os.path.basename(result_path),
    )
